version: "3"
services:
  react-app:
    image: react-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config

volumes:
  caddy-data:
    driver: local
  caddy-config:
    driver: local
